# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Toy AWS Authentication App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'amplify-tools'

  pod 'Amplify'
  pod 'AWSPluginsCore'
  pod 'AmplifyPlugins/AWSAPIPlugin'
  pod 'AWSMobileClient', '~> 2.12.1'      # Required dependency
  pod 'AWSAuthUI', '~> 2.12.1'            # Optional dependency required to use drop-in UI
  pod 'AWSUserPoolsSignIn', '~> 2.12.1'   # Optional dependency required to use drop-in UI

  # Pods for Toy AWS Authentication App

  target 'Toy AWS Authentication AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Toy AWS Authentication AppUITests' do
    # Pods for testing
  end

end
